[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]

axum = { workspace = true }
tokio = { workspace = true }
rumqttc = "0.25.1"
serde = { workspace = true }
serde_json = { workspace = true }
url = "2.5.4"
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
configuration = { workspace = true }

[workspace]
resolver = "3"
members = ["crates/configuration"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"


[workspace.dependencies]

# Error Handling
anyhow = "1"
thiserror = "2"


#configuration
config = { version = "0.15.22", default-features = false, features = [
  "toml",
  "yaml",
] }
dotenvy = "0.15"


# Data Serialization and Deserialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

#Observability and Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
  "env-filter",
  "fmt",
  "json",
] }
tracing-error = "0.2"


# Async Runtime and Utilites
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
rand = "0.10.2"
sha2 = "0.11"
base64 = "0.23"
uuid = { version = "1", features = ["v7", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
argon2 = "0.5"

# Database and ORM
sea-orm = { version = "2", features = [
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "macros",
  "with-chrono",
  "with-json",
  "with-uuid",
] }
sea-orm-migration = { version = "2", features = [
  "sqlx-postgres",
  "runtime-tokio-rustls",
] }

# HTTP Libraries
axum = { version = "0.8", features = ["macros", "tracing", "multipart", "ws"] }


#Proc Macro
inventory = "0.3"
paste = "1"
proc-macro2 = "1"
quote = "1"
syn = { version = "3", features = ["full"] }

#Member Crates
configuration = { path = "crates/configuration" }
